### ISSUE TITLE
Code used to create PLAbDab available?

### ISSUE THREAD

**Issue by astrobdr** [brennanaba/PLAbDab#7]
Hi first off, thanks for the amazing database!

It seems like this repo only contains code to query the already made database right?

Is the code used to create this from querying NCBI via Entrez available anywhere?

Thanks!

**Comment by brennanaba** [comment]
Hi Taeyoon Kim,

Thank you for your kind words about PLAbDab.

The majority of entries in PLAbDab are a curated version of data available in the NCBI database. For these cases, you can extract the full sequence using the following code. For example for the PLAbDab entry with ID AKW39254, you can extract its full sequence using the following script:

```python
from Bio import Entrez

plabdab_ID = "AKW39254"

with Entrez.efetch(db="protein", id=plabdab_ID, rettype="gb",retmode="xml") as handle:
    entries = Entrez.read(handle)

full_sequence = entries[0]["GBSeq_sequence"].upper()
```

I hope that helps!!

All the best,

Brennan

**Comment by astrobdr** [comment]
?

**Comment by brennanaba** [comment]
Hi Daniel,

Thank you for your kind words about PLAbDab.

You are right, this repo only contains the code to query the database.

The code used to create the database is not currently publicly available. However, to extract data from the NCBI database using Entrez you can use the following code:

```python
from Bio import Entrez

plabdab_ID = "AKW39254"

with Entrez.efetch(db="protein", id=plabdab_ID, rettype="gb",retmode="xml") as handle:
    entries = Entrez.read(handle)

sequence = entries[0]["GBSeq_sequence"].upper()
```

I hope that helps!!

All the best,

Brennan

**Comment by astrobdr** [comment]
Gotcha, thanks! A bit sad that the code to create the database is not public, but its ok.

What is plabdab_ID? Does it literally correspond to the same plabdab database that we can query using this repo?

**Comment by brennanaba** [comment]
Hi Daniel,

For entries scraped from the NCBI database, the plabdab ID will correspond to the LOCUS code used in NCBI (or a combination of them if the heavy and light chains come from a different NCBI entry). For example, the entry with plabdab ID QTW11010 was scraped from here: [https://www.ncbi.nlm.nih.gov/protein/QTW11010](https://www.ncbi.nlm.nih.gov/protein/QTW11010).

All the best,

Brennan
