### ISSUE TITLE
Database with url integrated 

### ISSUE THREAD

**Issue by immunomotivees** [brennanaba/PLAbDab#8]
Hello,

Thank you very much for this database, it is very helpful !
I saw in util.py that you build the function add_url_to_paired_data(df) but do you have any database that is already filled with these informations ?

Furthermore do you have any insight on how to retrieve target sequences based on information from paired_sequences.csv ?

Thanks for any insight you can provide
Best regards,
Celia

**Comment by brennanaba** [comment]
Hi Celia,

Thanks a lot for your kind comments about PLAbDab!!

You can generate a version of the database with urls by doing a search by keyword on the website using an empty keyword. 

Unfortunately, I am not aware of a general method to retrieve sequences for the targets. If you have a specific entry in mind, you can probably search for the antigen name in the NCBI protein database: https://www.ncbi.nlm.nih.gov/protein/

I hope that helps!!

All the best,

Brennan

**Comment by immunomotivees** [comment]
Hello Brennan,

Thank you very much for your answer

Best regards,
Celia
