### ISSUE TITLE
Are there any rabbit antibody in your database?

### ISSUE THREAD

**Issue by Frank-LIU-520** [brennanaba/PLAbDab#9]
I would like to get as many rabbit antibody as possible. I wonder how many rabbit antibody are there in your dataset?

**Comment by brennanaba** [comment]
Hi Frank,

You may want to manually check these. But I found around 500 paired rabbit
[rabbits.csv](https://github.com/user-attachments/files/18151321/rabbits.csv). You can likely find more, but a lot of the patent data does not have an organism label on it. 

All the best,

Brennan
